theme: jekyll-theme-minimal
title: MUME Open Source
description: MUME is a free multiplayer roleplaying game based upon J.R.R. Tolkien’s Middle-earth that has been continuously enhanced since fall ‘91. MUME stands for Multi-Users in Middle-earth.
logo: https://github.com/mume.png
